name: aribu
channels:
  - conda-forge
dependencies:
  - python=3.14
  - pytorch-gpu
  - torchvision
  - numpy
  - pandas
  - rasterio
  - geopandas
  - scikit-learn
  - scikit-image
  - scipy
  - matplotlib
  - tqdm
  - ipykernel
  - ipywidgets
  - jupyterlab
  - streamlit
  - pytest
  - pip
  - pip:
      - segmentation-models-pytorch
      - -e .
